steps:
  - id: "Docker Build"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/polls/polls:$COMMIT_SHA', '/workspace/django_gke/django' ]

  - id: "Docker Push"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/polls/polls:$COMMIT_SHA' ]

  - id: "Get SQL Proxy"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo "FROM us-central1-docker.pkg.dev/cronjobs-409106/polls/polls:$COMMIT_SHA
        COPY --from=gcr.io/cloud-sql-connectors/cloud-sql-proxy /cloud-sql-proxy /cloudsql/cloud-sql-proxy" > Dockerfile-proxy;
        docker build -f Dockerfile-proxy -t us-central1-docker.pkg.dev/$PROJECT_ID/polls/polls-proxy:$COMMIT_SHA .

  - id: "Migrate Database"
    name: "us-central1-docker.pkg.dev/$PROJECT_ID/polls/polls-proxy:$COMMIT_SHA"
    dir: sql-proxy
    env:
      - "MYSQL_HOST=127.0.0.1"
      - "MYSQL_PORT=3306"
      - "MYSQL_TYPE=mysql"
    secretEnv:
      - backend-secrets
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        /cloudsql/cloud-sql-proxy --port ${_MYSQL_PORT} ${_INSTANCE_CONNECTION_NAME} & sleep 2;
        cd /workspace/django_gke/django;
        ./manage.py migrate

  - id: 'deploy to kubernetes'
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters update prod-private --region us-central1 --enable-master-authorized-networks --master-authorized-networks $(curl -s http://ifconfig.io/ip)/32
        gcloud container clusters get-credentials prod-private --region us-central1 --project $PROJECT_ID
        kubectl -n polls set image deployment/polls polls=us-central1-docker.pkg.dev/cronjobs-409106/polls/polls:$COMMIT_SHA

substitutions:
  _INSTANCE_CONNECTION_NAME: cronjobs-409106:us-central1:prod-mysql
  _MYSQL_PORT: '3306'
  _MYSQL_TYPE: 'mysql'
  _MYSQL_PASSWORD_KEY: MYSQL_password
  _IMAGE_NAME: us-central1-docker.pkg.dev/cronjobs-409106/polls/polls:$COMMIT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/cronjobs-409106/secrets/backend-secrets/versions/1
      env: 'backend-secrets'
