steps:
  - id: "Docker Build"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/polls/polls:$COMMIT_SHA', '/workspace/django_gke/django' ]

  - id: "Docker Push"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/polls/polls:$COMMIT_SHA' ]

  - id: 'deploy to kubernetes'
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters update prod-private --region us-central1 --enable-master-authorized-networks --master-authorized-networks $(curl -s http://ifconfig.io/ip)/32
        gcloud container clusters get-credentials prod-private --region us-central1 --project $PROJECT_ID
        kubectl -n polls set image deployment/polls polls=us-central1-docker.pkg.dev/cronjobs-409106/polls/polls:$COMMIT_SHA
