apiVersion: apps/v1
kind: Deployment
metadata:
  name: polls
  namespace: polls
spec:
  selector:
    matchLabels:
      app: polls
  template:
    metadata:
      labels:
        app: polls
    spec:
      serviceAccountName: polls-service-account
      containers:
      - name: polls
        image: us-central1-docker.pkg.dev/cronjobs-409106/polls/polls:2cd2603da39ae1d9a4d602434ed0d63d16aab38f
        envFrom:
          - secretRef:
              name: polls
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--private-ip"
          - "--structured-logs"
          - "--port=3306"
          - "cronjobs-409106:us-central1:prod-mysql=tcp:3306"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu:    "1"
---

apiVersion: v1
kind: Service
metadata:
  name: polls
  namespace: polls
spec:
  type: ClusterIP
  selector:
    app: polls
  ports:
  - port: 8000
    targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polls
  namespace: polls
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - polls.moore.co.ke
    secretName: moores-letsencrypt-prod
  rules:
    - host: polls.moore.co.ke
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: polls
                port:
                  number: 8000
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: polls-service-account
  namespace: polls

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@amdava.org
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx